### ISSUE TITLE
Fix full OM test cases

### ISSUE THREAD

**Issue by MarianneSaugierRTE** [dynawo/dynawo#1104]
Current errors are:
For the SMIBStepPm:  "Illegal access of protected element lambdafPu".
For the HVDC test case and the associated HvdcVSCNoBlockingFunction.mo model in the BaseModel directory: "Illegal access of protected element PInjPu".

**Comment by MarianneSaugierRTE** [comment]
Errors related to protected variables could be easily fixed but then we get numerical errors when trying to simulate the Hvdc test case

**Comment by MarianneSaugierRTE** [comment]
@cossartque @RomainLosseauRTE @gautierbureau Could you please check the three full OM test cases and tell me which work fine, which doesn't (with error messages), and which OM version you are using (@gautierbureau you can run it which the command line you use in you automatic tool chain). I have different OM environments and none of them can simulate the three test cases properly...Thanks a lot :)

**Comment by cossartque** [comment]
On my side : 
- The SMIB case doesn't work because of an "Illegal access of protected element lambdafPu.". Otherwise it works well.
- The grid forming case works well.
- The HVDC case doesn't work for numerical reasons : "kinsols runs into issues retry with different configuration." and "Move forward with a less accurate solution.".
I am using OMCompiler v1.14.0-dev.26789+g1c369fe1a and OMSimulator v2.1.0-dev-147-g36ec2c7-linux.

**Comment by RomainLosseauRTE** [comment]
Same results as Quentin's
I am using OMCompiler v1.16.0-dev.578+g4fb5363aba and OMSimulator v2.1.0-dev-177-g0d19b0d-linux

**Comment by MarianneSaugierRTE** [comment]
Thanks a lot!

**Comment by adriguir** [comment]
@MarianneSaugierRTE is it fine at the moment?

**Comment by MarianneSaugierRTE** [comment]
> @MarianneSaugierRTE is it fine at the moment?

No not yet

**Comment by adriguir** [comment]
OK thanks, nothing urgent. Just wanted to know

**Comment by MarianneSaugierRTE** [comment]
HVDC test case still gives a numerical error see #1538
