### ISSUE TITLE
Environment variable DYNAWO_INSTALL_DIR is required in runtime environment

### ISSUE THREAD

**Issue by zamarrenolm** [dynawo/dynawo#1556]
Current version of Dynawo requires that `DYNAWO_INSTALL_DIR` environment variable is defined in the runtime environment. 
This has been recently introduced in `DYNCommon.cpp` when `getLibraryPathFromName` is called.

Maybe `DYNAWO_HOME` should be used at this point, instead of `DYNAWO_INSTALL_DIR`, that is a variable useful in the build environment, but was never required in the runtime environment as far as we know.

**Comment by gautierbureau** [comment]
For me the issue is the other way around. `DYNAWO_INSTALL_DIR` is in fact the variable we use at runtime to point to the installation at runtime (see https://github.com/dynawo/dynawo/blob/master/dynawo/sources/Launcher/dynawo.sh that is the main script to launch a dynawo distribution) on the contrary `DYNAWO_HOME` is only used in `envDynawo.sh` that is a script to deal with the development environment. In dynaflow-launcher we can use `DYNAWO_HOME` to point to the installation of Dynawo at the cmake level (ie `-DDYNAWO_HOME` on the cmake command line) but in https://github.com/dynawo/dynaflow-launcher/blob/master/scripts/dynaflow-launcher.sh it is `DYNAWO_INSTALL_DIR` that should have been used to have something similar to `dynawo.sh`. For me we just need to use `DYNAWO_INSTALL_DIR` in this script and get rid of  `DYNAWO_HOME` in it.
