### ISSUE TITLE
[Models] Delete the intermediate angle variable associated into the injector Idq model

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#2172]
This causes problems in dae mode when solving the problem because the associated angle is instantaneously switching from Pi to -Pi.

**Comment by cossartque** [comment]
In order to delete the variable UPhase, calculated as the arg of uPu, I propose that UPhase becomes an input of the injector model. Then of course, whenever InjectorIDQ model is used, a proper PLL must be added to the model to provide this UPhase to the injector. For the moment InjectorIDQ is used in the WECC models and in the HVDC VSC models.

**Comment by adriguir** [comment]
Test cases for the Wind Turbine alone (without the plant controller) have to be updated - they perhaps were not there at the time the development for this issue began. 
Parameters for the PLL should be filled, otherwise the behavior is quite erratic.
