### ISSUE TITLE
NaN at initialization (IStator0Pu)

### ISSUE THREAD

**Issue by ErwanGuichard49** [dynawo/dynawo#2286]
This issue has been detected on GitLab branch 460_add_mteret, test case _nrt/data/SMIB/SMIB_GoverGt2VRSemipol2/SMIB.jobs_, it involves the model _DynawoRTE/Electrical/Controls/Machines/VoltageRegulators/Specific/Thermal/VRSemipol2_INIT.mo_ and the preassembled file _dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousFourWindingsGoverGt2VRSemipol2Tfo.xml_.

In this model, Is0Pu is declared as a variable since it is a parameter of the dynamic model. Is0Pu is furthermore used in the equations of the initialization model, something I have not done in any other model. Is0Pu is connected through an initConnect to IStator0Pu of the generator.

The local initialization (as seen in _dumpInitValues-SM.txt_) results in several nan values, which prevent the simulation from running. Surprisingly, the INIT model for the whole configuration (hereby attached in txt format) is run successfully by OpenModelica.
[GeneratorSynchronousFourWindingsGoverGt2VRSemipol2Tfo_INIT.txt](https://github.com/dynawo/dynawo/files/8560461/GeneratorSynchronousFourWindingsGoverGt2VRSemipol2Tfo_INIT.txt)

Moreover, replacing Is0Pu in the equations of _VRSemipol2_INIT.mo_ by a constant allows the simulation to run successfully under Dynawo.

**Comment by rosiereflo** [comment]
The NaN comes from the current equation that contains sqrt(i.re*i.re +i.im*i.im) and initially i.re = i.im = 0. 
We thus obtain a NaN in the Jacobian value for this equation relatively to i.re and i.im.
Removing the internal connection solves the issue only because the variable computed by this equation becomes a calculated variable and this equation is then removed from the resolution.
Adding a start value to i solves the problem.
