### ISSUE TITLE
Consider dummy der variables as differential

### ISSUE THREAD

**Issue by rosiereflo** [dynawo/dynawo#2329]
The dummy derivatives generated by OpenModelica are considered as being algebraic today, the idea of this ticket is to try to consider them as differential

**Comment by bongrainmat** [comment]
test case for this issue
[testIndex2.zip](https://github.com/dynawo/dynawo/files/8730470/testIndex2.zip)

The current model works fine in OMEdit. In dynawo, the model compiles but the test case doesn't run, as the following assert is raised:  numF != indexY_.size(). This means that the total number of differential equations doesn't match the total number of differential variables.
After analysis of the equations system of the transformer, we find out index number if our DAE is > 1. In order to deal with it, OpenModelica derives two equations of the system and chooses two variables as dummy der (in order to make the problem square), creating a mismatch between the number of differential equations and variables. This problem isn't related to the dummy der part of the algorithm as even when submitting an already derived problem (meaning dummy der don't need to be generated), this inadequacy still happens. 
It is due to the tagging function for the equations/variables used by dynawo in the initialization process. --> adapt the current tagging function to avoid the mismatch.
