### ISSUE TITLE
IEC Active/Reactive current priority flag

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#2934]
It seems that the parameter Mqpri (used in the current limiter) is not taken into account. Setting it to false also leads to priority to reactive current in my case: the expected behavior is that in this case priority is given to active power.

From a quick analysis, it seems that this comes from the combination of the booleanConst and booleanToInteger blocks.

FYI @joyelfeghali @cossartque

**Comment by cossartque** [comment]
We have done some tests with Gerard and it seems that it's working properly.

When in reactive priority, iqmax = output of a combiTable between 0 and 1
When in active priority, iqmax = min(output of a combiTable between 0 and 1, sqrt(IMax² - Iq²)). In the test case that we have, IMax = 1.3 and Iq doesn't get high enough (the short-circuit is not frank because of sqrt < 0 issues) so sqrt(IMax² - Iq²) stays higher than the output of a combiTable between 0 and 1 which means that changing mqpri is useless in this case.

When taking a smaller IMax (1.1 for instance), we start seeing a difference. @GerardThevenon is preparing a test case to show it.
