### ISSUE TITLE
The result does not seem to be affected by the voltage setpoint change (IEC2015)

### ISSUE THREAD

**Issue by marcosmc** [dynawo/dynawo#3341]
Analyzing the possible combinations of control modes of the dynamic model "**IECWPP4BCurrentSource2015**" we have found a case that seems to be anomalous.

The attached case has been configured to activate voltage control mode:
**MqG = 0** "General Q control mode (0-4) : Voltage control (0), Reactive power control (1), Open loop reactive power control (2), Power factor control (3), Open loop power factor control (4)"
**MwpqMode = 3** "Control mode (0 : reactive power reference, 1 : power factor reference, 2 : UQ static, 3 : voltage control)"

The event introduced is an **increase in the voltage setpoint of 2% in the 20th second** of the simulation.

After analyzing the result of the dynamic simulation we have obtained a flat curve in the area of ​​the event trigger (except for a mismatch in the initialization of the case).

![image](https://github.com/user-attachments/assets/b6d74078-3712-4508-ba87-5e95dff61b86)

[IEC2015.zip](https://github.com/user-attachments/files/16195060/IEC2015.zip)

**Comment by louisg-rte** [comment]
I've checked the files that you sent us and it seems that a parameter has to be changed in order to get a consistent output:
- WPP_URef0Pu is the voltage reference for the voltage setpoint of the WT : Here, considering that MwpqMode = 3, the WP control sends to the WT a $\Delta U$ setpoint but then the WT has to know what is the voltage reference to compute the voltage setpoint as : $U=U_{ref0}+\Delta U$. So basically we will choose **WPP_URef0Pu=1.**

In addition if you want to check the voltage magnitude instead of the real part you can just add the variable WPP_wPPControl2015_complexToPolar_len in the crv and you will see that this variable follow the setpoint of this example:
![Capture d’écran de 2024-07-17 08-50-12](https://github.com/user-attachments/assets/700be5c1-e0ec-4412-ad8d-ea2b4c118628)
