### ISSUE TITLE
Improve the initialization implementation

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#902]
In the current initialization implementation available into Dynawo, there are a few treatments that could be optimized because they are done on the same object, which is not fully utilized by the written code.

The idea would be to avoid searching into the structures several times when we are still working onto the same component.

**Comment by lecourtoisflo** [comment]
Also, this issue tracks the optimization of code for code clarification (code quality improvement) concerning the API. The APIs are using a pattern interface with an implementation class and a factory which is not adapted and can cause performance drops since interfaces are slower than base classes.
So we remove this pattern, putting implementation classes inside the interface class (chich is no longer a c++ interface)
